#!/usr/bin/env bash
#

imports () {
  cat <<EOM
import synthesis.Definitions._
val answer = choose((x: Int) => x > 41)
EOM
}

sbt package && /scala/inst/29/bin/scala -Yrepl-sync -i <(imports) -Xplugin:synthesis-plugin.jar -classpath synthesis-plugin.jar
